### ISSUE TITLE
[BUG] Problem building docs on Window using "make html"

### ISSUE THREAD

**Issue by cjmayers** [ericmjl/pyjanitor#464]
# Brief Description

Following the instructions on the [contributions](https://pyjanitor.readthedocs.io/contributing.html) page fails when trying to `make html` a symbolic link privilege not held error

# System Information

- Operating system: Windows  
- OS details (optional):  10 Enterprise 
- Python version (required): Python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

# Minimally Reproducible Code

after activating the env and traversing to the ..\pyjanitor-dev\docs folder
`make html`

# Error Messages

```
Traceback (most recent call last):
  File "C:\conda3x64\envs\pyjanitor-dev\lib\site-packages\sphinx\config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "C:\conda3x64\envs\pyjanitor-dev\lib\site-packages\sphinx\util\pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "c:\workspace\cjmayers\CODE\git_workspaces_external\pyjanitor\docs\conf.py", line 31, in <module>
    notebooks.symlink_to("../examples/notebooks")
  File "C:\conda3x64\envs\pyjanitor-dev\lib\pathlib.py", line 1330, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held
```

**Comment by cjmayers** [comment]
I have found that executing this command in an Administrator Powershell instance works and creates the not only ..\pyjanitor-dev\docs\_build directory with all the correct files but it also creates a shortcut to notebooks in the ..\docs directory.

Now if the `make html` is run through either normal instance or an Administrator instance of Powershell the following error occurs:

```
(pyjanitor-dev) c:\workspace\cjmayers\CODE\git_workspaces_external\pyjanitor\docs>make html
Running Sphinx v2.1.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\conda3x64\envs\pyjanitor-dev\lib\site-packages\sphinx\config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "C:\conda3x64\envs\pyjanitor-dev\lib\site-packages\sphinx\util\pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "c:\workspace\cjmayers\CODE\git_workspaces_external\pyjanitor\docs\conf.py", line 29, in <module>
    if not notebooks.exists():
  File "C:\conda3x64\envs\pyjanitor-dev\lib\pathlib.py", line 1339, in exists
    self.stat()
  File "C:\conda3x64\envs\pyjanitor-dev\lib\pathlib.py", line 1161, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'notebooks'
```

**Comment by cjmayers** [comment]
If the notebook shortcut that was created in Administrator Powershell instance is removed (..\pyjanitor-dev\docs\notebooks) then we are go back to square one which requires an Admin to execute `make html`

After looking at the properties of the notebooks shortcut the properties for Target: and Start in: are blank making it a broken shortcut 

![01_shortcut_sm](https://user-images.githubusercontent.com/44857844/61188822-845d2b80-a64a-11e9-8d29-3b064f05e533.png)

**Comment by cjmayers** [comment]
A work around seems to be creating a junction where the synatx is `mklink /J "path to junction link" "path to target folder"`

The actual command needed for this bug is `mklink /J notebooks ..\examples\notebooks` which is executed from a normal shell in the ..\pyjanitor-dev\docs directory

Once this junction is created then `make html` works from a normal shell
